### ISSUE TITLE
Fix logo

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-frontend#12]

**Comment by Yasinaaa** [comment]
Expectation
<img width="281" alt="Screenshot 2020-05-13 at 13 30 17" src="https://user-images.githubusercontent.com/10158025/81801983-ef52e980-951d-11ea-803b-3184587d99f5.png">

Reality
<img width="470" alt="Screenshot 2020-05-13 at 13 26 50" src="https://user-images.githubusercontent.com/10158025/81801925-d64a3880-951d-11ea-8096-a5d28b939a0b.png">

P.S. Text of logo also part of the logo, because we don't have information about font and etc. Creator of logo said that it inseparable things.

**Comment by aabounegm** [comment]
Is it possible to get information about the font, or at least try to match it as much as possible? Otherwise, it couldn't be translated
