### ISSUE TITLE
Add search view

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-frontend#31]
When to 'search' click, icon color changes to green and a text field appears
<img width="571" alt="Screenshot 2020-06-07 at 10 04 58" src="https://user-images.githubusercontent.com/10158025/83962496-9c631c80-a8a6-11ea-89ad-715a8f1b7b80.png">
When you start typing, similar texts are searched throughout the whole site and need to show in which section it was found (Reports,  News, Money Gathering, etc)
<img width="570" alt="Screenshot 2020-06-07 at 10 05 10" src="https://user-images.githubusercontent.com/10158025/83962543-f95ed280-a8a6-11ea-8a53-9605729defac.png">
If a similar text is found, it is highlighting to green
<img width="570" alt="Screenshot 2020-06-07 at 10 05 29" src="https://user-images.githubusercontent.com/10158025/83962590-388d2380-a8a7-11ea-9ca8-8c50b18c3c62.png">
If there is no coincidence show such view
<img width="570" alt="Screenshot 2020-06-07 at 10 05 36" src="https://user-images.githubusercontent.com/10158025/83962663-de409280-a8a7-11ea-9ce4-7e63800a53b6.png">

**Comment by R-Mosolov** [comment]
I am planning to realise following steps to solve the issue:
1) create the **header-bar** directory into **components** directory;
2) move **HeaderBar.vue** component to **header-bar** directory;
3) create the **Searcher.vue** component into **header-bar** directory. This component will keep main structure, styles and logic of searcher suggestions for a user;
4) create the **toggle-searcher.js** plugin into **plugin** directory. This component will keep the logic of opening and closing searcher window;
5) the **HeaderBar.vue** component will use these component from Vuetify (**Searcher.vue**, **toggle-searcher.js**);
6) probably, also I create the **add-green-color.js** plugin into **plugin** directory. If searcher plugins will be more than 1 I create the separate **searcher** directory for keeping these components into **plugin** directory.

**Comment by aabounegm** [comment]
- 1\. The components directory was structured such that any common components (used in all pages) are in the root directory, and any components specific to one page are in a folder named exactly like the page (with the `.vue` part). If you want to organize these common components more, I suggest having a folder called "common" (or something similar) in which we put these components or at least their smaller sub-components.

- 4\. The logic of opening/closing the search input belongs to the Search component. It is definitely not a plugin, and not something that needs to be run before Vue is mounted. It is part of the Vue component for searching.

If there are utility functions that are common to many components and are mostly pure or self-contained (in that they don't modify Vue or any global state), it is better to create a `utils` folder for them and import them wherever needed.

**Comment by R-Mosolov** [comment]
Did I understand right that you recommend to reorganize file structure as follows?

**root**
|--**components**
|----common
|------Searcher.vue
|----HeaderBar.vue
|--**utils**
|----toggle-searcher.js

**Comment by aabounegm** [comment]
Yes, that's correct.
I also suggested not having `toggle-searcher.js` and instead putting the functionality right in the component, but that depends on what exactly you plan on writing there. That will be in the PR review

**Comment by R-Mosolov** [comment]
Done! The solution of the issue keeps here: 
https://github.com/Zakyat/zakyat-frontend/tree/roman_front

**Comment by aabounegm** [comment]
Please create a Pull Request and don't move to Done manually. It will be moved once the PR is approved and merged
