### ISSUE TITLE
Add 'View all' text for gathering items

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-frontend#33]
On the main page, we going to show precisely 3-5 open gatherings. That's why we need to add 'View others' button to open a page with all gathering (In Figma - Main_Last_Gathering_Item)
<img width="693" alt="Screenshot 2020-06-07 at 11 18 25" src="https://user-images.githubusercontent.com/10158025/83963726-bf92c980-a8b0-11ea-84bd-3e33e09cb15a.png">

**Comment by chackydude** [comment]
I am planning to realise following steps to solve the issue:

- [ ] Add new SwipeSlider
- [ ] Center the label and add link to the gathering page
