### ISSUE TITLE
Add all gatherings page

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-frontend#34]
In Figma - Aids

Opens when:
1) click to 'Посмотреть все' at the end of gatherings slider (Issue #33)

<img width="760" alt="Screenshot 2020-06-07 at 11 26 57" src="https://user-images.githubusercontent.com/10158025/83963901-d554be80-a8b1-11ea-9037-f56a79215e71.png">

**Comment by chackydude** [comment]
I am planning to realise following steps to solve the issue:

- [ ] Create new page (~/pages/gathering/index.vue)
- [ ] Add gathering cards on the page
- [ ] Use already existing components for creating gathering cards
- [ ] Fix some margins and padings of existing components
