### ISSUE TITLE
'News' page

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-frontend#37]
Opens when clicking to 'Новости' in the header
In Figma - News
<img width="631" alt="Screenshot 2020-06-07 at 13 52 10" src="https://user-images.githubusercontent.com/10158025/83967009-8a917180-a8c6-11ea-91c0-57dc9b12b2d6.png">

When clicking to 'Показать по тегам' opens a dialog for search above 'sadaka' dialog
In Figma - Search News with tags
<img width="1006" alt="Screenshot 2020-06-08 at 20 07 58" src="https://user-images.githubusercontent.com/10158025/84059765-ca8a4e80-a9c3-11ea-8bd2-6e1231bf7fa4.png">

**Comment by Ural-2001** [comment]
Here are my steps to solve this issue:
1. Create a news.vue file into pages directory
2. Create a news directory into components directory
3. I think I am going to divide a page into 3 parts, tags slider + tags filter, news list and sadaka dialog
4. Create a Tags.vue file into components/news directory 
5. Create a NewsList.vue file into components/news directory 
6. Create a Sadaka.vue file into components/news directory 
7. For news cards and payment card am going to use Vuetify cards
8. For slider with tags I want to try Swiper and SwiperSlide that you’ve used in SliderBar.vue component
