### ISSUE TITLE
'Zakat' page

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-frontend#38]
Opens when click to 'Выплатить закят' in header
In Figma - Zakat. Zero Interface
<img width="535" alt="Screenshot 2020-06-08 at 20 12 45" src="https://user-images.githubusercontent.com/10158025/84060202-7b90e900-a9c4-11ea-80d8-ff5ae3189533.png">

When a user clicks to a green highlighted text have to open helper dialog with an explanation.
For example, how is it looks in 'Meduza' mass media
![photo_2020-03-28_18-10-02](https://user-images.githubusercontent.com/10158025/84060921-adef1600-a9c5-11ea-8773-08b9af7da0f9.jpg)

All texts for an explanation dialogs and for questions section are constant values. Yasina will give it to the developer of this task directly, just write her in Telegram.

Also, pay attention for zakat calculator
In Figma - Zakat. Input
<img width="186" alt="Screenshot 2020-06-08 at 21 22 11" src="https://user-images.githubusercontent.com/10158025/84066234-46899400-a9ce-11ea-9677-bdb9aa890568.png">

**Comment by Yasinaaa** [comment]
1) For the first iteration could use any video
2) Information about gold price in Russia need to be taken from https://www.cbr.ru/development/DWS/
3) On 'По данным ЦБРФ' click should be open this page https://www.cbr.ru/key-indicators/
4) Zakat is paid in the amount of 2.5 percent of a person’s condition, exceeding the size of nisab.
(0,025 х money)

**Comment by stwer1998** [comment]
I plan to divide the page into the following components and implement them:
1. video component
2. information component
3. questions answers component
4. zakat calculator component

**Comment by aabounegm** [comment]
Video playback doesn't need a dedicated component. The HTML `<video>` element suffices.
Make sure to make use of i18n, even if you write only the Russian version.
