### ISSUE TITLE
'About news' page

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-frontend#43]
When a user clicks to specific news should be opened 'About news' page
In Figma - About news
<img width="569" alt="Screenshot 2020-06-12 at 09 30 14" src="https://user-images.githubusercontent.com/10158025/84472101-584d8e80-ac8f-11ea-87e7-44e85cd8a740.png">

The grey rectangle in the right it would be a place for a banner
On 'Смотреть все' click opens all news page

**Comment by Ural-2001** [comment]
Steps to solve this issue:
1. Create a news directory into pages
2. Create an _id.vue file for a specific news page
3. Maybe it will be better to move news.vue into new ‘news’ directory and rename it as ‘index’
4. I am going to use rows and cols for the layout and v-card for the news itself and for cards in another news section

**Comment by aabounegm** [comment]
Resolved in #59
