### ISSUE TITLE
'About us' page

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-frontend#44]
Opens when click to 'О фонде' in the header
In Figma - Zakayat. About organization [New]

1)<img width="878" alt="Screenshot 2020-07-13 at 13 53 32" src="https://user-images.githubusercontent.com/10158025/87297033-73baec00-c510-11ea-975b-8e31b73fed74.png">

2)
<img width="710" alt="Screenshot 2020-07-13 at 13 53 46" src="https://user-images.githubusercontent.com/10158025/87297050-787fa000-c510-11ea-95d4-3086b30f840c.png">

All files you can download from [about_us_files.zip](https://github.com/Zakyat/zakyat-frontend/files/4913977/about_us_files.zip)

- [ ] Set correct images from about_us_files.zip according to their names, because in Figma it's just a pattern of images.

- [ ] When you click on the picture should open an extended full version of the image

3) When you click on the 'устав' and 'лист записи' should open files from previous zip file.
<img width="710" alt="Screenshot 2020-07-13 at 13 53 54" src="https://user-images.githubusercontent.com/10158025/87297051-79183680-c510-11ea-98ab-442c376ccd01.png">

4) Show correct place in map as has written in the end 'г.Казань, ул.Г.Тукая 89/14'
<img width="714" alt="Screenshot 2020-07-13 at 13 54 05" src="https://user-images.githubusercontent.com/10158025/87297053-79b0cd00-c510-11ea-8605-50ceeaf1d5ed.png">

**Comment by Ural-2001** [comment]
For this issue I am going to:
- Create about.vue file into pages directory
- Create the main card which is on the top of the page in the about.vue file
- Create card for the members of the charity and make another component for it
- Create components for 'Свидетельства', 'Документы' and 'Контакты'

**Comment by aabounegm** [comment]
Resolved in #70
