### ISSUE TITLE
'Send help request' page. Type children_with_disabilities_or_with_severe_diseases

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-frontend#63]
- [x] 1) When a user clicks to 'Получить помощь' in main menu opens this page [in Figma - Help Request].
 
- [x] 2) [In Figma - 'Help request']

<img width="980" alt="Screenshot 2020-07-22 at 19 07 36" src="https://user-images.githubusercontent.com/10158025/88200379-be461200-cc4e-11ea-9973-fadfe0a5d1ee.png">

A user has 11 choices, but in this issue, you need to create a view for the first type - **children_with_disabilities_or_with_severe_diseases**.
[In Figma - 'Help request. Show items']

For each type need to show such fields:

- [x] Text: "Для выбранной категории вам нужно заполнить информацию о себе, супруге и о всех своих детях"

- [x] "Информация о вас" section
<img width="522" alt="Screenshot 2020-07-23 at 08 32 21" src="https://user-images.githubusercontent.com/10158025/88254811-161c6180-ccbf-11ea-9d22-d3ea4f2943e2.png">

- [x] "Ребёнок, нуждающейся в помощи" section
<img width="537" alt="Screenshot 2020-07-23 at 08 33 33" src="https://user-images.githubusercontent.com/10158025/88254885-5aa7fd00-ccbf-11ea-84a4-20c4a6ac5019.png">

- [x] If the user chose martial status anything except 'alone' and 'other' need to show obligately 'spouse' section
<img width="582" alt="Screenshot 2020-07-23 at 09 02 38" src="https://user-images.githubusercontent.com/10158025/88256282-888f4080-ccc3-11ea-9594-ae415566e677.png">

- [x] In case if their have other children
<img width="548" alt="Screenshot 2020-07-23 at 09 09 22" src="https://user-images.githubusercontent.com/10158025/88256550-49adba80-ccc4-11ea-8a06-4be333048bf7.png">

- [x] Add functionality to load images in underlined text click 

- [x] On 'Изменить' button click return to choose help type list view

- [x] On 'Написать заявление и отправить' button click show error dialog if user didn't input all fields [in Figma - ''Help Request. Input required fields"]

- [x] Error fields show with #EB3050 color

**Comment by chackydude** [comment]
I am planning to realise following steps to solve the issue:

- [ ] Add link on the main page to the send-help page
- [ ] Add main content component with a links to the others help-request components
   example of file system structure: 
**root**
|--components
|----help-request
|-------HelpRequestContent.vue (containt links to all categories)
|-------ChildrenWithDisabilitiesHelp.vue
|-------(here can be components for other categories)
- [ ] Lay out ChildrenWithDisabilitiesHelp.vue component
- [ ] Set up routing between components of gategories

**Comment by Yasinaaa** [comment]
Fix/Add these items in the same order

- [ ] 

<img width="341" alt="Screenshot 2020-07-24 at 11 23 52" src="https://user-images.githubusercontent.com/10158025/88373638-dcbc2280-cda0-11ea-8e66-76deaeafe568.png">

- [ ] 
<img width="589" alt="Screenshot 2020-07-24 at 11 21 33" src="https://user-images.githubusercontent.com/10158025/88373634-da59c880-cda0-11ea-8458-f6e997e55674.png">

**Comment by aabounegm** [comment]
I cannot find these screenshots in Figma. Is there a new link? This is the one I have: https://www.figma.com/file/Uawx1aTAf6LJjjG2xgoV6v/Web-Zakyat-Done-me

**Comment by chackydude** [comment]
Yea, where is one more link, check that -> https://www.figma.com/file/MZvfpVKRb7sgZdcRhssTKt/Web-Zakyat?node-id=0%3A1

Help Request, Help Request Show Items

But @Yasinaaa found some mistakes in the design and asked me to change a little bit existing pages in Figma. As a result that page contains some components from others.
