### ISSUE TITLE
Should be fixed content size and empty space around the edges

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-frontend#9]
Like in a picture

**Comment by Yasinaaa** [comment]
![photo_2020-05-10_13-26-09](https://user-images.githubusercontent.com/10158025/81800480-94b88e00-951b-11ea-9dd4-e5349eceed2e.jpg)

**Comment by Yasinaaa** [comment]
![photo_2020-05-10_13-26-09](https://user-images.githubusercontent.com/10158025/81800654-d3e6df00-951b-11ea-92b7-ea762ad0b391.jpg)

**Comment by aabounegm** [comment]
I don't understand what is the problem. Are you saying that the page should be narrower and that the black header and green section shouldn't actually have 100% width? Or is this just about the arrows in the carousel?
